### ISSUE TITLE
SPIKE: Investigate frameworks

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#11]
What's required for 2.0/ missing from Create 1.0?

What frameworks allow for routing via URL?
- ***Ionic***
- ***next.js***
- ***Gatsby***
- ***create-react-app***

- svelte
- flutter
- remix run (new)

**Comment by mannycolon** [comment]
# Sources

- https://www.robertcooper.me/comparing-nextjs-and-gatsbyjs-static-site-generation
- https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs
- https://medium.com/frontend-digest/which-to-choose-in-2020-nextjs-vs-gatsby-1aa7ca279d8a
- https://www.solutelabs.com/blog/gatsby-js-vs-next-js-which-one-to-choose-when
- https://blog.logrocket.com/next-js-vs-gatsbyjs-a-developers-perspective/
- https://dev.to/jameesy/gatsby-vs-next-js-what-why-and-when-4al5
- https://pagepro.co/blog/next-js-vs-gatsby-which-one-to-choose/
- https://buttercms.com/blog/nextjs-vs-gatsbyjs-picking-the-right-support-react-framework
- https://blog.jakoblind.no/gatsby-vs-next/
- https://jaredpalmer.com/gatsby-vs-nextjs
- https://www.popwebdesign.net/popart_blog/en/2020/11/nextjs-vs-gatsby-which-is-your-best-2021-choice/
- https://nextjs.org/docs/getting-started
- https://www.gatsbyjs.com/docs/
- https://create-react-app.dev/docs/getting-started/
- https://nextjs.org/docs/migrating/from-gatsby
- https://www.youtube.com/watch?v=xC4Yq_mXvPM

**Comment by mannycolon** [comment]
- https://dev.to/jameesy/gatsby-vs-next-js-what-why-and-when-4al5#:~:text=The%20fundamental%20difference%20is%20Next,HTML%20page%20from%20the%20server.

**Comment by mannycolon** [comment]
# Findings

- create-react-app will create you a boilerplate of a React project, but Nextjs/Gatsbyjs are not just boilerplates, but toolkits, laying the foundations and then giving you a set of instructions on how to build the house as well. Thus,

   - create-react-app - Lays the foundations of a React Project. The rest is up to you.

   - Gatsby & Next - Lay the foundations of a React Project. Give you guidelines on how you should build on top of them.

**Comment by mannycolon** [comment]
# Ionic React
One Codebase, Any Platform


## Ionic vs Next.js
- TBD

**Comment by mannycolon** [comment]
# Create React App v4

Create React App is an officially supported way to create single-page React applications. It offers a modern build setup with no configuration.

-  Lays the foundations of a React Project. The rest is up to you.
- Create React App eliminates grueling tasks like installing and configuring Webpack and Babel which are preconfigured and hidden, so you can focus on coding. This means less stuff to learn and all you need to do to start creating a React app is run any of the commands above.
- Although Create React App comes with pre-configuration for Webpack and Babel, it does not force you to use its own configuration. You can eject from Create React App and add your custom configurations to your taste.
- Create React App doesn't prescribe a specific routing solution, but React Router is the most popular one.
   - https://reactrouter.com/web/example/basic
   - Note that you may need to configure your production server to support client-side routing before deploying your app.
   - https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing
-  Fast Refresh
- Typescript support
- Create React App supports code splitting using the dynamic import() directive. Instead of returning the values exported by the module, it will instead return a Promise that resolves into these values. As a result, modules imported this way won’t be included in the final bundle, but built into separate files. This allows you to reduce the size of the final bundle and load content on demand.
- Progressive Web Apps

**Comment by mannycolon** [comment]
# My Top 3

- Next.js
- Create React App
- Ionic React
