### ISSUE TITLE
Retrieve the Original Language scriptures from the latest Catalog Next Release

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#214]
Issue:
---
GLs cannot edit the OrigL scripture resources and the GL will be aligned to the released OrigL, therefore the default OrigL scripture resources should be the released text. If the user wants to open the master for that resource then the user can change the resource in the scripture card settings. Since Catalog Next is where future releases of our resources will be released, the latest releases should be retrieved from Catalog Next.

DoD:
---
The default original languages scriptures are the latest published version in the Catalog.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie - fixed in https://develop--gateway-edit.netlify.app/, build v1.0.0 build 1723ce6

Not any easy way to test this, but here is one approach: 
- check console log, for NT should have entries for ugnt such as `fetch & parse unfoldingWord/el-x-koine/ugnt/v0.20/...` and not `fetch & parse unfoldingWord/el-x-koine/ugnt/master/...`.  Or in the case of OT books should have entries for uhb such as: `fetch & parse unfoldingWord/hbo/uhb/v2.1.19/...`

**Comment by cckozie** [comment]
Appears to be working correctly. This is what I'm seeing in v1.0.0 build fb5cd9b
fetch & parse test_org2/en/ult/master/act act: 2217.200ms
19.2aac94aab69b63a8181b.js:1 fetch & parse unfoldingWord/el-x-koine/ugnt/v0.21/act act: 3955.600ms
19.2aac94aab69b63a8181b.js:1 fetch & parse test_org2/en/ust/master/act act: 3938.600ms
19.2aac94aab69b63a8181b.js:1 fetch & parse unfoldingWord/el-x-koine/ugnt/v0.21/act act: 5134.700ms

**Comment by birchamp** [comment]
@cckozie yes they need to be the same.  Looking into UGNT.

**Comment by elsylambert** [comment]
v1.0.0 build fb5cd9b.
Works fine as per the testing help given by Bruce. Console shows the version of the Original Language.

**Comment by cckozie** [comment]
tC and gatewayEdit are now both showing ugnt v0.21 and hbo v2.1.21. Passing this issue and removing the question.
