### ISSUE TITLE
Unable to cancel the Network error modal when user is on Project page

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#229]
Issue:
---
When the user is on the project page the network error should have a single button called 'Retry' that just attempts to redraw the screen.  

Because we should prompt them to do something before they try again, change the text on the network error prompt to read: "No network connection was detected. Please reconnect your computer to the network and try again." 

DoD:
---
The network error modal on the Project page only has a retry button and directs the user to reconnect.

Details:
---
Separated this from #130
When the connection is lost while user is on the Project page and user tries to navigate the verses from the top navigation, the Network connection error message is shown, which is fine, but when the Cancel button is clicked, it is stuck cause the app tries to load the previous page but fails and the error message is shown again. Please see the video for more clarity:
https://images.zenhubusercontent.com/310359593/8b629b69-8529-4565-b146-983b17ed49d5/no_connection_error.mp4

**Comment by PhotoNomad0** [comment]
@elsylambert It looks like you had networking disconnected and you pressed cancel several times, and then finally pressed retry.  
- When you click cancel the app tries to redraw the screen which initiates fetching content for the resource panes, which leads to the network error coming up again showing "Please check your network connection. No network connection was detected."
- when you click retry, the app tells the browser to reload the page.  This of course fails unless the network connection is re-established.

Note that the error here is for network disconnect (WIFI not connected or Ethernet connect not working)

A couple of suggestions here for network errors drawing the Workspace page:
1.  The retry button which does a page reload is a problem here - it is overkill when the network connection has been restored.  And if the network is still disconnected the app disappears and we see a browser error message (not a good user experience).
2.  I think we should just have a single button called retry that just attempts to redraw the screen.  There is no point for a cancel button that just clears the error prompt, because until the network is connected again the user can do nothing.  I think it is good for the network error prompt to keep coming back up until the network problem is fixed.  They user do anything anyway until network is working.
3.  We should change the text on the network error prompt to read something like "No network connection was detected. Please reconnect your computer to the network and try again."  We should prompt them to do something before they try again.

@mannycolon @birchamp @cckozie

**Comment by elsylambert** [comment]
Points 2 and 3 makes sense to me. Having just the retry button until the network connection is restored and with the right error prompt as in point 3, gives enough information to the user.

**Comment by birchamp** [comment]
@PhotoNomad0 yes I like that solution.

**Comment by PhotoNomad0** [comment]
@elsylambert In latest develop build v1.0.0 build f27cc47

**Comment by elsylambert** [comment]
Not seeing the issue in v1.0.0 build 1c04778. The modal shows  an appropriate message with a Retry button.
