### ISSUE TITLE
Handle verse spans in the scripture viewer

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#329]
Issue
—-
USFM that contains verse spans - \v 2-4 should display the text for that verse in gatewayEdit. The spanned text should be displayed for all verses in the span. ie. A verse span of \v 2-4 should show the text whether verse 2 or 3 or 4  is chosen in the reference navigator. The highlighting should work as if the text is a single verse.

DoD:
—-
Scripture that contains combined verses in a span should be displayed and highlighted in the scripture cards.

Details:
—-
Often translators have to combine the text of two or more verses in order to properly communicate the text correctly. The is represented in USFM by a verse marker followed by two numbers separated by a hyphen.  (\v 2-4). The user expects a verse span to function just like all the other verses for all the checks for all the verses included in the span. An example of how this works is the scripture pane in translationCore.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert Currently in GWE we display the verse spans, but highlighting is not working.  Phil 1:15-17 in en_ust is a good test example because it is both a span and is aligned:

<img width="1012" alt="Screenshot 2023-03-25 at 6 58 00 AM" src="https://user-images.githubusercontent.com/14238574/227713291-68ae549b-965a-47c9-98f1-4e27e8b02b99.png">

**Comment by elsylambert** [comment]
@PhotoNomad0 Please see the attached screenshot: in the latestGWE v1.1.0 build 2747aff QA server.
![Screenshot 2023-03-28 at 9.01.57 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/556b6b3e-5887-4531-a0aa-cf0d6ea1ce12)
The highlighting is not showing up even after adding Original Quote to the Quote section. Was the highlighting fixed in this build?

**Comment by PhotoNomad0** [comment]
@elsylambert  It works if you change occurrence to 1

**Comment by elsylambert** [comment]
Thanks @PhotoNomad0 it works.

**Comment by PhotoNomad0** [comment]
@elsylambert FYI - the alignment on the UST for that verse span `15-17` is very strange. It is not very linear.   Maybe they got the occurrences mixed up?

**Comment by elsylambert** [comment]
Yeah @PhotoNomad0 I noticed that. Could it be data issue? I tried with occurrence 2 but it does not highlight with it.

**Comment by PhotoNomad0** [comment]
> Yeah @PhotoNomad0 I noticed that. Could it be data issue? I tried with occurrence 2 but it does not highlight with it.

Hmm...both 1 & 2 are working for me when I use the same word you chose.

**Comment by elsylambert** [comment]
![Screenshot 2023-03-28 at 9.39.21 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f47c0b0e-9330-4b72-974b-9243ccadf86b)

**Comment by PhotoNomad0** [comment]
@elsylambert do we need to meet after standup?  I can bring up tCore to see how the ust is aligned, but It looks like it is highlighting properly.  Maybe I need to google chiasm from the note and see if that means a mixed up order?

**Comment by PhotoNomad0** [comment]
@elsylambert maybe we should create an issue for GWE to highlight/flag invalid fields? - such as invalid occurence number, missing supportReference, Notes, etc. ?  @birchamp

**Comment by danielklapp** [comment]
Tested with v1.1.0 build 2747aff QA. Working properly
