### ISSUE TITLE
Typing in scripture lags when the verse is long

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#526]
Per Steven Wunrow, typing in the scripture window lags when there are more than ~50 words and many changes. 

DoD
---
Typing remains normal after completely changing a 50 word verse.

**Comment by PhotoNomad0** [comment]
@elsylambert OK, I was able to reproduce.  Investigating.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp The fix is in GWE develop v2.3.0 build 0eda053

**Comment by elsylambert** [comment]
Verified in v2.3.0 build 0eda053 QA.  Not seeing lag in typing when we have a big chunk of text typed into the verse. It shows a spinner OnBlur, after the edit is done and then Save button is enabled. When the spinner is running, the action buttons on the card are disabled which is intentional to avoid clicks when the system is validating the alignments. Works ars expected.

**Comment by danielklapp** [comment]
Agree that there’s no lag when typing in large verses and after an edit is complete a spinner appears letting user know something is happening. Action buttons are working as expected. Tested with v2.3.0 build 0eda053 QA.
