### ISSUE TITLE
Move Add Button in TWL to Action Row

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#542]

**Comment by elsylambert** [comment]
@kintsoogi is this change merged in Develop branch?

**Comment by elsylambert** [comment]
v2.1.0 build f845565 QA on https://develop--gateway-edit.netlify.app/. Seeing a number of problems:
1. When we click on TWL row + to add a row, the add row dialog shows a different verse in Reference and the Original Quote.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4889ca1b8dda1b1fc950ca482378d4b9e8c994f3/Screenshot%202023-11-14%20at%209.40.23%E2%80%AFAM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ef0740d58e9d1162909fcaa867cd6bd7cc475e7/Screenshot%202023-11-14%20at%209.41.20%E2%80%AFAM.png)


2. When in OT books, the Original Quote field is empty.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9d4d6e022b10b496f8fb85b5fb791600f5eac47/Screenshot%202023-11-14%20at%209.42.40%E2%80%AFAM.png)


3. After we click on Add on Add row dialog, the save button is not enabled on the TWL card. The changes are saved in a different verse due to problem mentioned in Step 1.

**Comment by birchamp** [comment]
@kintsoogi was this a necessary technical need?  This seems like a bad user experience and we eliminated it as an option early on.

**Comment by birchamp** [comment]
@elsylambert @kintsoogi we should only fill in the new reference, new id, occurrence, and a dropdown for the TWs.

**Comment by birchamp** [comment]
@elsylambert @kintsoogi let's break out the dropdown as a separate issue.

**Comment by elsylambert** [comment]
@birchamp I rewrote the issue #506 and moved to Backlog. This issue defines the drop-down for new rows for TWLs.

**Comment by danielklapp** [comment]
When clicking on Add Tsv Row button under Actions, the add row dialog does show correct verse in Reference and the Original Quote. Looks good with v2.1.0 build 65fd995 QA.
