### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#82]
- Will translation-helps-RCL handle editing? 
  - If yes, is it ready for editing? 
  - If not, then what RCL will be used? 
- What is necessary on the back end in order to add resource editing and saving to the user's branch? 
- How are we going to handle branched workflow? 
  - When is the user's branch created (Users have requested that the branch is only created on save)?
  - When do we update from Master?
  - How do we handle conflicts?
- Do we need a Catalog next RCL? Does GRT need to change?
- When in the workflow do users need to be informed that changes will be lost? 
- How will the app handle lost tokens on an attempted save (multi-sessions)? 
- What else is unaccounted for?
- How do we handle TWL and subsequent files?

**Comment by BincyJ** [comment]
@birchamp need to know details on how the flow works.
- On blur? 
- In terms of UI- Edit/ Save /Submit how would it work?

**Comment by mannycolon** [comment]
# Create a new context/custom hook for editing files

- EditContentProvider
   - const { loading, error, updateContent } = useEdit(PAYLOAD);

**Comment by mannycolon** [comment]
- **Will translation-helps-RCL handle editing?** Yes
  - **If yes, is it ready for editing?** An editing feature will have to be added.
- **What is necessary on the back-end in order to add resource editing and saving to the user's branch?** 
We need to add the feature to create user branches to push edits to it.
- **How are we going to handle branched workflow?** 
  - **When is the user's branch created?** Users have requested that the branch is only created on file save.
  - **When do we update from Master?** Should we add a feature to allow users to update a resource card from master?
  - **How do we handle conflicts?** Add feature to handle merge conflicts where the user is given a multiple-choice question to select what they want to keep just like in translationCore.
- **Do we need a Catalog next RCL? Does GRT need to change?** For this feature we don't need a Catalog next RCL but we'll need to modify GRT.
- **When in the workflow do users need to be informed that changes will be lost?** Not sure what this means.
- **How will the app handle lost tokens on an attempted save (multi-sessions)?**

**Comment by mannycolon** [comment]
https://github.com/unfoldingWord/gateway-edit/issues/200#issue-891302414

**Comment by mannycolon** [comment]
Moved Birch comment from #200 

Users want to be able to edit resources and save them to a branch on DCS. 
For editing, users want to:
--
  * **Edit only certain fields**
     * Markdown files - TranslationAcademy and TranslationWords articles
     * In TranslationNotes OccurrenceNote, OccurrenceNumber, SupportReference, Original Quote should be editable
        * On blur the scripture highlight should update when the Original Quote or OccurrenceNumber are edited
        * On blur the TranslationAcademy article should update when the user edits the SupportReference 
     * In TranslationWord Links the Original Quote and Occurrence field should be editable


--
  * **Know what field they're currently editing:**
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/d33d8ac4-16a2-4318-afa4-6b947c3f0bf7)
--
 * **save their changes to a per user branch**
  * users should be able to click a save button to save their work
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/362877cb-2e01-48b9-8c34-8ba2a3921b48)
--
* **know when a file has been changed**
   * Each editable card should have a save icon with the tooltip "Save".
   * use https://fonts.google.com/icons?selected=Material+Icons:save for unsaved. 
   * use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asave for saved

--
* **switch between preview and markdown**
   * Each editable card should have a preview icon with the tooltip "Preview" when in Markdown mode and "Markdown" when in Preview mode
   * use https://fonts.google.com/icons?selected=Material%20Icons%3Apreview for formatted
   * use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apreview for markdown
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/049b373e-fdb1-4bc3-b961-11e34e9be658)

--
 * **be notified when they can lose their changes**
  When the user can potentially lose data due to changing records or scripture references they should be notified:
A modal should inform the user of what resources have unsaved changes:
  ```
Some resources have unsaved changes that will be lost if you continue:
  TranslationAcademy
  TranslationWords

Continue without saving | Cancel | Save All
```
