### ISSUE TITLE
App crash if user is not part of an org

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#87]
There's a crash if the user isn't part of an organization.  This should be an error. "The application can not continue. The current username is not part of a DCS organization. Please contact your administrator."

See https://github.com/unfoldingWord/create-app/issues/57 for screenshots of initial crash.

**Comment by elsylambert** [comment]
Not able to test with a user that I created on DCS. It gives error message that username does not exist.

**Comment by elsylambert** [comment]
On a new browser with a fresh login, a non-org user can see the message as in the snapshot:
![Screen Shot 2021-03-30 at 10.42.36 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/17d87b96-ee45-4bf9-8c40-6f5f186df8b4)
However, if there were previous logins with a user having an org, the non-org user can directly get to the project page after login.
#98 since the user data is persisted on the browser,  a non-org user can get to the project page from previous org user login.

**Comment by elsylambert** [comment]
v0.9.0 build 736dc08
The issue with non-org users getting to project page has been resolved.

**Comment by cckozie** [comment]
In v0.9.0 build f601ed4 a non-org user is pushed to the screenshot above after logging in.

**Comment by elsylambert** [comment]
Tested in gE_App crash Test
