### ISSUE TITLE
Clicking on the OLQuote in tN card  brings the card to 1st note(in case of multiple notes)

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#90]
Issue: 
---
Clicking on the OL Quote jumps the TN card to the first record in the verse.  The card should remain as it is. 

DoD:
---
Clicking on the TN OL Quote should highlight the aligned text (if it isn't already), but the TN card should not change.

Details: 
---
Here is the recording:
- when there are multiple notes with highlights, the note that does not have a tA article linked, shows this behaviour.
https://images.zenhubusercontent.com/310359593/76e5ffcb-4238-46d4-bafa-2c9ba5322671/video_mp4__1534x890_.mp4

**Comment by PhotoNomad0** [comment]
@mannycolon - I see a problem happening here: https://github.com/unfoldingWord/translation-helps-rcl/blob/main/src/hooks/useCardState.js#L13

When the quote is clicked in tN, then SupportReference is undefined because selectedQuote is an empty object so it sets the itemIndex to 0.  Don't know why selectedQuote would be empty, but should we always be resetting the itemIndex to 0 when SupportReference is undefined?

**Comment by mannycolon** [comment]
@PhotoNomad0 Yeah that sounds like a good idea.

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build 3e62f25

**Comment by elsylambert** [comment]
Not seeing this issue in v0.9.0 build 3e62f25.

**Comment by cckozie** [comment]
Tested in Test tN Clicking and Highlighting
